version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: foundation_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: foundation
      POSTGRES_PASSWORD: daine
      POSTGRES_DB: foundation
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 